name: Development Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Rust nightly
      run: rustup toolchain install nightly
    - name: Check code styles
      run: cargo fmt --check
    - name: Lint dumper
      run: cargo +nightly clippy --package dumper --target x86_64-unknown-none -- -D warnings
      env:
        RUSTFLAGS: --cfg fw="1100"
    - name: Lint obfw
      run: cargo clippy --package obfw --all-features -- -D warnings
